### ISSUE TITLE
Add peer dependency for react-redux@^5.0.0

### ISSUE THREAD

**Issue by leontastic** [jschr/form-provider#6]
Getting this error from running `npm list` in a project using react-redux-form-provider and react-redux 5.0.3:

```
peer dep missing: react-redux@^3.0.0 || ^4.0.0, required by react-redux-form-provider@0.1.9
```

**Comment by jschr** [comment]
this is dependency warning with react-redux-form-provider because it specifies react-redux 3 or 4. Since react-redux is now at 5 I need to updated the package. Nothing for you to do here and it's just a warning. I'll fix this in my package when I can.

**Comment by jschr** [comment]
Oh haha. this is my package.

**Comment by jschr** [comment]
Think I just need to add `|| ^5.0.0`. Will fix this in next release
